# Endcoding

Encoding means converting the categorical data into numeric form

## One hot Encoding

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('loan_data_set.csv')
df.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [3]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [4]:
# first filling the missing values
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])

In [5]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

### Using Get Dummies

In [6]:
en_data = df[['Gender', "Married"]]
en_data.head(3)

  Gender Married
0   Male      No
1   Male     Yes
2   Male     Yes

In [7]:
# pd.get_dummies(en_data)  # returns in true and false
pd.get_dummies(en_data).astype(int)
# pd.get_dummies(en_data).astype(int).info()

     Gender_Female  Gender_Male  Married_No  Married_Yes
0                0            1           1            0
1                0            1           0            1
2                0            1           0            1
3                0            1           0            1
4                0            1           1            0
..             ...          ...         ...          ...
609              1            0           1            0
610              0            1           0            1
611              0            1           0            1
612              0            1           0            1
613              1            0           1            0

[614 rows x 4 columns]

### Using Scikit Learn

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe = OneHotEncoder()
# ohe.fit_transform(en_data)    # returns a sparse matrix

ar = ohe.fit_transform(en_data).toarray()
ar

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [10]:
en_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Gender   614 non-null    object
 1   Married  614 non-null    object
dtypes: object(2)
memory usage: 9.7+ KB

In [11]:
pd.DataFrame(ar, columns=["Gender_Female" ,"Gender_Male",	"Married_No",	"Married_Yes"]).head(3)

   Gender_Female  Gender_Male  Married_No  Married_Yes
0            0.0          1.0         1.0          0.0
1            0.0          1.0         0.0          1.0
2            0.0          1.0         0.0          1.0

In [12]:
en_data.head()

  Gender Married
0   Male      No
1   Male     Yes
2   Male     Yes
3   Male     Yes
4   Male      No

In [13]:
ohe = OneHotEncoder(drop='first')

ar = ohe.fit_transform(en_data).toarray()
ar

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [14]:
pd.DataFrame(ar, columns=["Gender_Male", "Married_Yes"]).head(5)

   Gender_Male  Married_Yes
0          1.0          0.0
1          1.0          1.0
2          1.0          1.0
3          1.0          1.0
4          1.0          0.0

---

## Label Encoding

Used for unsequence/unorderd data

In [15]:
df = pd.DataFrame({
    "name":['cow', 'dog', 'cat', 'white', 'black'],
})
df

    name
0    cow
1    dog
2    cat
3  white
4  black

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()
le.fit_transform(df['name'])

array([2, 3, 1, 4, 0])

In [18]:
df['en_name'] = le.fit_transform(df['name'])

df

    name  en_name
0    cow        2
1    dog        3
2    cat        1
3  white        4
4  black        0

In [19]:
df = pd.read_csv("loan_data_set.csv")
df.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [20]:
df['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [21]:
la = LabelEncoder()
la.fit(df['Property_Area'])

LabelEncoder()

In [22]:
la.transform(df['Property_Area'])

array([2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       1, 0, 1, 1, 1, 2, 2, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 0, 2, 2, 2, 2, 0, 0, 1, 1,
       2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 0, 2, 1,
       2, 1, 0, 1, 1, 0, 1, 2, 0, 2, 0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 2, 1, 0, 0, 2, 1, 1, 2, 1, 2, 2, 0, 1, 0, 0, 2, 0,
       2, 1, 0, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 1, 1, 0,
       0, 1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 1, 0, 1, 0, 2,
       1, 2, 1, 1, 2, 2, 1, 1, 2, 0, 2, 1, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1,
       2, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2,
       2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 0,
       1, 0, 1, 2, 0, 2, 2, 2, 0, 1, 1, 1, 1, 2, 1, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 0, 2, 2, 1, 0, 2, 0, 2, 0, 2,
       0, 0, 1, 1, 0, 0, 0, 2, 1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 2,
       2, 1, 2, 2, 2, 1, 0, 0, 2, 1, 0, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 0,
       0, 0, 1, 2, 0, 2, 2, 1, 1, 1, 2, 2, 0, 0, 1, 0, 1, 0, 1, 1, 0, 2,
       2, 2, 0, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 0, 0, 2, 1, 2, 1,
       2, 2, 0, 1, 2, 0, 1, 1, 0, 1, 2, 0, 1, 0, 1, 2, 0, 0, 1, 2, 2, 2,
       0, 1, 0, 2, 2, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 1, 2, 1, 1, 2, 2, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2,
       0, 1, 1, 0, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 1, 2, 0, 0, 1, 1,
       1, 0, 0, 2, 1, 2, 1, 2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 1, 0, 1, 0,
       2, 2, 2, 2, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 2, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 0, 1, 0,
       0, 0, 2, 2, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 2, 0, 2, 0, 2, 2, 2, 2,
       2, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 0,
       2, 0, 0, 1, 0, 2, 2, 0, 2, 0, 1, 2, 1, 0, 0, 0, 0, 2, 2, 1])

In [23]:
df['Property_Area'] = la.transform(df['Property_Area'])

In [24]:
df['Property_Area'].head()

0    2
1    0
2    2
3    2
4    2
Name: Property_Area, dtype: int32

In [25]:
df['Property_Area'].unique()

array([2, 0, 1])

---

## Ordinal Encoding

In [26]:
df = pd.DataFrame({"Size":['s', 'm', 'l', 'xl', 's', 'm', 'l', 's', 's', 'l', 'xl', 'm']})
df.head(3)

  Size
0    s
1    m
2    l

In [27]:
df['Size'].unique()

array(['s', 'm', 'l', 'xl'], dtype=object)

In [28]:
ord_data = [['s', 'm', 'l', 'xl']]

### Using Scikit Learn

In [29]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
# oe = OrdinalEncoder() # by default it encodes based on alphabets
oe = OrdinalEncoder(categories=ord_data) # here we specify that what should be the order
oe.fit_transform(df[['Size']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [3.],
       [1.]])

In [31]:
df['en_size'] = oe.fit_transform(df[['Size']])
df

   Size  en_size
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0

In [32]:
df['en_size'].unique()

array([0., 1., 2., 3.])

### Using Map Function

In [33]:
# create a dictionary first
ord_data1 = {"s":"0", "m":"1", "l":"2", "xl":"3"}
ord_data1

{'s': '0', 'm': '1', 'l': '2', 'xl': '3'}

In [34]:
df['Size'].map(ord_data1)

0     0
1     1
2     2
3     3
4     0
5     1
6     2
7     0
8     0
9     2
10    3
11    1
Name: Size, dtype: object

In [35]:
df['en_size_map'] = df['Size'].map(ord_data1)
df

   Size  en_size en_size_map
0     s      0.0           0
1     m      1.0           1
2     l      2.0           2
3    xl      3.0           3
4     s      0.0           0
5     m      1.0           1
6     l      2.0           2
7     s      0.0           0
8     s      0.0           0
9     l      2.0           2
10   xl      3.0           3
11    m      1.0           1

In [36]:
# create a dictionary first
ord_data2 = {"s":"11", "m":"12", "l":"33", "xl":"57"}
ord_data2

{'s': '11', 'm': '12', 'l': '33', 'xl': '57'}

In [37]:
df['en_size_another'] = df['Size'].map(ord_data2)

In [38]:
df

   Size  en_size en_size_map en_size_another
0     s      0.0           0              11
1     m      1.0           1              12
2     l      2.0           2              33
3    xl      3.0           3              57
4     s      0.0           0              11
5     m      1.0           1              12
6     l      2.0           2              33
7     s      0.0           0              11
8     s      0.0           0              11
9     l      2.0           2              33
10   xl      3.0           3              57
11    m      1.0           1              12

---

In [39]:
df = pd.read_csv('loan_data_set.csv')
df.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [40]:
df['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [41]:
order = [["Rural", "Semiurban", "Urban",]]

In [42]:
oe = OrdinalEncoder(categories=order)

df['Property_Area'] = oe.fit_transform(df[['Property_Area']])

In [43]:
df['Property_Area'].head(10)

0    2.0
1    0.0
2    2.0
3    2.0
4    2.0
5    2.0
6    2.0
7    1.0
8    2.0
9    1.0
Name: Property_Area, dtype: float64

---